<?php
namespace frontend\models;
use yii\db\ActiveRecord;

class Books extends ActiveRecord{
    public function rules()
    {
        return [
            [['title','writer','price','webaddr'],'required']
        ]; // TODO: Change the autogenerated stub
    }
}